apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-publisher-config
  labels:
    app: blog-publisher
data:
  PORT: '3000'
  NOTES_PATH_PREFIX: notes/blogs/
  GITHUB_OWNER: fohte
  GITHUB_REPO: fohte.net
  GITHUB_DEFAULT_BRANCH: master
  IMAGE_VARIANT_WIDTHS: '640,1280,1920'
  R2_PUBLIC_BASE_URL: https://cdn.fohte.net
