issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte@11088009/blog-publisher@1243002116:ref:refs/heads/(main|master)$
claim_pattern:
  job_workflow_ref: ^fohte/blog-publisher/\.github/workflows/boilerplate-update\.yml@[^@]+$
permissions:
  contents: write
  pull_requests: write
  workflows: write
